name: my_project_main
description: "Aplikasi Navigasi Rumah Sakit STELLA."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Daftar package yang dibutuhkan oleh aplikasi
  google_fonts: ^6.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  dio: ^5.4.3+1
  geolocator: ^12.0.0
  panorama_viewer: ^2.0.7
  flutter_compass: ^0.8.0
  mobile_scanner: ^5.1.1
  webview_flutter: ^4.8.0
  video_player: ^2.8.6
  http: ^1.2.1
  cupertino_icons: ^1.0.6
  pathfinding: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/guidance/
    - assets/panorama/
    - assets/video/